### PR TITLE
♻ Add a more robust way of getting controller URL.

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

Replaces the way we get the Copntroller uri with a more robust approach. After https://github.com/ImperialCollegeLondon/drunc_ui/pull/258#discussion_r1869934336 comment made by Chris

Fixes # (issue)

## Type of change

- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass (eg. `python -m pytest`)
- [x] The documentation builds and looks OK (eg. `python -m sphinx -b html docs docs/build`)
- [x] Pre-commit hooks run successfully (eg. `pre-commit run --all-files`)

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

### CODE REVIEW

**Review by cc-a — APPROVED** [review]
Great. Thanks for this @dalonsoa

**Review by AdrianDAlessandro — COMMENTED** [review]
Not sure how to test this one. The talk_to_controller script doesn't use this, does it?

**Comment by cc-a** [comment]
@AdrianDAlessandro Stand up the docker compose stack and boot the test session then from a Django shell in the `app` container:

```python
from controller.controller_interface import get_controller_uri
get_controller_uri()
```

You should get an ip address and port back.

**Review by AdrianDAlessandro — APPROVED** [review]
Following what @cc-a said above, I do indeed get an IP and port back (after running `boot_test_session`)

**Pull request merged**
