### PR TITLE
Disable running upload codecov for bots

### LINKED ISSUE #104: Disable codecov for bot created PRs
https://github.com/ImperialCollegeLondon/dune_processes/pull/100#issuecomment-2370903408

### PR DESCRIPTION
**Pull request by TinyMarsh**
# Description

This pull request changes the CI workflow so that coverage reports are only uploaded to Codecov for pull requests not created by specific automated bots.

Fixes #104

## Type of change

- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass (eg. `python -m pytest`)
- [ ] The documentation builds and looks OK (eg. `python -m sphinx -b html docs docs/build`)
- [x] Pre-commit hooks run successfully (eg. `pre-commit run --all-files`)

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

### CODE REVIEW

**Review by cc-a — APPROVED** [review]
Seems fine to me @alexdewar could you take a look at this one.

**Review by dalonsoa — APPROVED** [review]
We (they) used the same approach in Virtual Ecosystem - a bit more complex as they had to exclude Windows and MacOS. Maybe we need to do the same here?

https://github.com/ImperialCollegeLondon/virtual_ecosystem/blob/f7f909908c312a2a4cb7649148dee64f341835ba/.github/workflows/ci.yml#L50-L58

**Review by alexdewar — APPROVED** [review]
Looks fine to me. I'm assuming the issue was that this step was failing for dependabot?

Just FYI, repo secrets like the `CODECOV_TOKEN` aren't available to dependabot for security reasons, which can break things like this. If you *did* want to make it available to dependabot, you can add it to the "dependabot secrets" too.

But just skipping it seems like the better approach here.

**Review by jamesturner246 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
